# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-05 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_flsaclaim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flsaclaim',
            name='content',
        ),
    ]
