# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-05 20:00
from __future__ import unicode_literals

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('webapp', '0003_remove_flsaclaim_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='flsaclaim',
            name='content',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='description', to='cms.Placeholder'),
        ),
    ]
