# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-16 14:43
from __future__ import unicode_literals

from django.db import migrations
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_flsaclaim_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litigation',
            name='description',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True),
        ),
    ]
