# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-16 14:51
from __future__ import unicode_literals

from django.db import migrations
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True),
        ),
    ]
